server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.94.22.154:3306/clazz?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: clazz
    password: clazz
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.deb.clazz
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true